name: Feeds

on:
  push:
    branches:
      - main
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  feeds:
    runs-on: ubuntu-latest
    name: Build static feeds site
    permissions:
      contents: write
      issues: write
    steps:
      - name: Run Action
        uses: llun/feeds@4.6.3
        with:
          storageType: files
          customDomain: feeds.llun.dev
